version: "2"

services:
  sensebox-sketches:
    build: .
    ports: 
      - "3924:3924"
    environment:
      SENSEBOX_SKETCHES_SERVER_CERT: |-
        -----BEGIN CERTIFICATE-----
        MIIDQTCCAikCCQCQRj0qr0PhGTANBgkqhkiG9w0BAQsFADCBjDEaMBgGCSqGSIb3
        DQEJARYLY2FAc2Vuc2Vib3gxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxETAP
        BgNVBAcMCE11ZW5zdGVyMREwDwYDVQQKDAhzZW5zZUJveDEXMBUGA1UECwwOc2Vu
        c2VCb3hEZXZPcHMxFDASBgNVBAMMC3NrZXRjaGVzX2NhMB4XDTE3MDExMjEyNDE1
        OVoXDTI3MDExMDEyNDE1OVowgb8xHjAcBgkqhkiG9w0BCQEWD3NlcnZlckBzZW5z
        ZWJveDELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05SVzERMA8GA1UEBwwITXVlbnN0
        ZXIxETAPBgNVBAoMCHNlbnNlQm94MRcwFQYDVQQLDA5zZW5zZUJveERldk9wczES
        MBAGA1UEAwwJbG9jYWxob3N0MS8wLQYDVR0RDCZETlMuMT1za2V0Y2hlcyxETlMu
        Mj1zZW5zZWJveC1za2V0Y2hlczCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEAD0P
        HnUq1wNsMKeNg7gQrTw5sQEz2wTlrlS6wzkTJ6lYTUlK4jkMb2hwUV4721Q3Izdk
        3DbY/CNqOTTee/cEUaUrAVnizri2aHGFzXZlPMrcs6/I9Lu3S40OqGgsnAV24CDT
        Ukd0cNi+nVIdGSHpx/Z05AUdME3NljbAStC31FyzCc1yMA0GCSqGSIb3DQEBCwUA
        A4IBAQDGMCNQVHAn/QaVNJZXXprJy+YvCyk9zZQEhOmvLhgPGRcFN/+5n0Y/H+sj
        AZ/lP+ErzTRjYzTJQsfKCSw+rT2Igh+ZutdMbGQ5nu56vZ+WU517A1NNqHLz7eg7
        SlzjwFSzNbT3iVQoB54kYPxMhVbDvNkxdYMZyHLeaAMbgBXYfVRjnkOpYK/hHmio
        ks5thkEQ7tKsiGKxC/ES8GgvaELiyWbpsnMAWuOL2yrF/SaxoUk9fszkJgVRClmK
        4gSRHqkQj2yJhNTW5OaeZRm0btCjLZ/lOP138/MdW5E2XlQ9TLkXOKXIDBZ8dw50
        GnSf3FPMxTcMLWhkajyi8Kt1N0vh
        -----END CERTIFICATE-----
      SENSEBOX_SKETCHES_SERVER_KEY: |-
        -----BEGIN EC PARAMETERS-----
        BgUrgQQAIw==
        -----END EC PARAMETERS-----
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIA1jKgyYIF8K8k/3PZXFayy5b2iOCeC6qKe76wAzIjKFnuXbDAxyHi
        2I5rSvj9RZmETX87LX6Kff9nlKf6EmMI3PGgBwYFK4EEACOhgYkDgYYABAA9Dx51
        KtcDbDCnjYO4EK08ObEBM9sE5a5UusM5EyepWE1JSuI5DG9ocFFeO9tUNyM3ZNw2
        2Pwjajk03nv3BFGlKwFZ4s64tmhxhc12ZTzK3LOvyPS7t0uNDqhoLJwFduAg01JH
        dHDYvp1SHRkh6cf2dOQFHTBNzZY2wErQt9RcswnNcg==
        -----END EC PRIVATE KEY-----
      SENSEBOX_SKETCHES_CA_CERT: |-
        -----BEGIN CERTIFICATE-----
        MIID7TCCAtWgAwIBAgIJALYNwt1bXZ/2MA0GCSqGSIb3DQEBCwUAMIGMMRowGAYJ
        KoZIhvcNAQkBFgtjYUBzZW5zZWJveDELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05S
        VzERMA8GA1UEBwwITXVlbnN0ZXIxETAPBgNVBAoMCHNlbnNlQm94MRcwFQYDVQQL
        DA5zZW5zZUJveERldk9wczEUMBIGA1UEAwwLc2tldGNoZXNfY2EwHhcNMTcwMTEy
        MTI0MTUzWhcNMjcwMTEwMTI0MTUzWjCBjDEaMBgGCSqGSIb3DQEJARYLY2FAc2Vu
        c2Vib3gxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxETAPBgNVBAcMCE11ZW5z
        dGVyMREwDwYDVQQKDAhzZW5zZUJveDEXMBUGA1UECwwOc2Vuc2VCb3hEZXZPcHMx
        FDASBgNVBAMMC3NrZXRjaGVzX2NhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA5QgvPpYUsApoIGEymK4mhZg1Q9xXg3jTqUGYE/Mue+3EwqJaOq4/KEDF
        kL/ow+sKS5eHqExKaw7B4ezqlJGqopBwNSrc8UnMi2ISs6avU4KMcygGwMpyZFxg
        bh1NWaKsSAfQPe6uP5uB6YR1gy+YgHECo7I7XbUZzoRjbRSJfA4tLY6sxveSZHTl
        9xE5xWAKipMV9pva5CSnfD7R2kf4Yzfn9Oykyw3kvi7v+qyoN4DV71inphK7U6XV
        gT6O3Ri68Z6CR5JdSsS+zgg2Ve14zk7U1Y8hMbLxonXa+BE2x7KGLv32sPZULG5m
        iUhTemMsuXHNtToEWPjConPmmipJVwIDAQABo1AwTjAdBgNVHQ4EFgQUQvMr8O7k
        h46L3b6pE1Zoy93sPeQwHwYDVR0jBBgwFoAUQvMr8O7kh46L3b6pE1Zoy93sPeQw
        DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAp/Yi9TUWFi8PUtrDy6WO
        fj0jY+wgiiI1B7qIu6oUeb2C6q9GCawjw/6zMRc7S3XW2TQwSqR/Dvq1Bw9Y0v6G
        R34KqVBvN1540jdlZWyYbXfvyvYygSIzh2B8CMrilBg0mOUJzQw20kmTbUes6PsL
        +cE4u3d/21bH/5qHJbd6E8WuW44CxplLmiQy69lvAOD3UsYF15jhUunxQEepp4yZ
        GKSTVRQbK80o+2WgAz2eHHUK8SdT7GMIwhi38pieeABZjR+nL9+BP87HqrFlQwuq
        6MMZMMP+wuO/99hu/uoMXZSzAWqpGAYOZh8PI06p3PMdmmQ+FPr6z3AWmaQe4PEB
        /Q==
        -----END CERTIFICATE-----