version: "2"

services:
  compiler:
    image: sensebox/sensebox-sketches
    networks:
      - compiler-network
    volumes:
      - build-cache:/app/src/arduino-ide/build-cache
      - sketch-cache:/tmp

networks:
  compiler-network:

volumes:
  build-cache:
  sketch-cache:
